# We need Python 3 for the tests, but, if we add Python 3 as a language, it will be
# installed in a virtualenv where bin/python points to Python 3.
# Then "python clang-format-diff" is spawned and this ends up using Python 2 instead
# of the required Python 2.7.
language: generic

os:
  - linux
  - osx

# On Ubuntu:
# - coreutils is for readlink.
# - Python 2.7 for clang-format-diff.
# - Python 3.4 for the actual tests.
before_install:
  - >
    if [ "$TRAVIS_OS_NAME" = osx ]; then \
        brew update && \
        brew upgrade python && \
        brew install \
            clang-format \
            shellcheck \
            && \
        sudo pip3 install pylint; \
    else \
        sudo apt-get update && \
        sudo apt-get install -y \
            clang-format-3.8 \
            coreutils \
            python2.7 \
            python3-pip \
            python3.5 \
            shellcheck \
            && \
        sudo pip3 install virtualenv && \
        virtualenv --python=python3.5 venv-for-travis && \
        . ./venv-for-travis/bin/activate && \
        pip install pylint && \
        deactivate; \
    fi

script:
  - ./run-checks
